libs =
import libs += glbinding%lib{glbinding}
import libs += glm%lib{glm}
import libs += assimp%lib{assimp}

import libs += libsfml-graphics%lib{sfml-graphics}
import libs += glfw%lib{glfw}

import libs += libimgui-platform-glfw%lib{imgui-platform-glfw}
import libs += libimgui-render-opengl3%lib{imgui-render-opengl3}

import libs += libgeometrycentral%lib{geometrycentral}
import libs += libigl-core%liba{igl-core}

exe{hyperreflex}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"

if ($cxx.target.system != 'win32-msvc')
  cxx.libs += -pthread
